services:
  extractor_api:
    image: personal-finance-app-extractor:dev
    environment:
      DB_PATH: /data/trusted/results.db
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"

  classifier_api:
    image: personal-finance-app-classifier:dev
    environment:
      DB_PATH: /data/trusted/results.db
      MODEL_CONFIG_YAML: /app/backend/classification/artifacts/model_config.yaml
    volumes:
      - ./data:/data
      - ./hf_cache:/root/.cache/huggingface
    ports:
      - "8001:8001"
    depends_on:
      - extractor_api

  frontend:
    image: personal-finance-app-frontend:dev
    environment:
      EXTRACTOR_API_URL: http://extractor_api:8000
      CLASSIFIER_API_URL: http://classifier_api:8001
    ports:
      - "8501:8501"
    depends_on:
      - extractor_api
      - classifier_api